# tools/sanity/check_01_minimal_db.py
from __future__ import annotations

import argparse
import tempfile
from pathlib import Path

from proof_scaffold.mm_emit import append_p_block
from proof_scaffold.verify import verify


def main() -> None:
    ap = argparse.ArgumentParser(description="Step 01: minimal Metamath database sanity check.")
    ap.add_argument("--mmverify", required=True, help="Path to mmverify.py")
    ap.add_argument(
        "--fixture",
        default="fixtures/sanity/01_minimal_db.mm",
        help="Path to the Step 01 fixture .mm file",
    )
    args = ap.parse_args()

    mm_verifier = Path(args.mmverify).resolve()
    fixture_path = Path(args.fixture).resolve()

    mm_src = fixture_path.read_text(encoding="utf-8")

    # Step 01 theorem:
    # Re-prove the trivial axiom ax-id.
    # This checks that the minimal database structure is complete and consistent.
    out_src = append_p_block(
        mm_src=mm_src,
        label="sanity.01",
        stmt="|- ( ph -> ph )",
        proof_labels=["wph", "ax-id"],
        comment="generated by Step 01 (minimal database sanity)",
    )

    with tempfile.TemporaryDirectory() as td:
        out_mm = Path(td) / "out.mm"
        out_mm.write_text(out_src, encoding="utf-8")
        verify(mm_verifier, out_mm, timeout_sec=30)

    print("SANITY 01 OK")


if __name__ == "__main__":
    main()
