# tools/sanity/check_02_stack_machine.py
from __future__ import annotations

import argparse
import tempfile
from pathlib import Path

from proof_scaffold.mm_emit import append_p_block
from proof_scaffold.verify import verify


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Step 02: Metamath proofs as stack programs."
    )
    ap.add_argument("--mmverify", required=True, help="Path to mmverify.py")
    ap.add_argument(
        "--fixture",
        default="fixtures/sanity/02_stack_machine.mm",
        help="Path to the Step 02 fixture .mm file",
    )
    args = ap.parse_args()

    mmverify_py = Path(args.mmverify).resolve()
    fixture_path = Path(args.fixture).resolve()

    mm_src = fixture_path.read_text(encoding="utf-8")

    # Step 02 theorem:
    # We re-prove the axiom ax-1 using explicit stack discipline.
    #
    # Stack execution:
    #   wph  -> push (wff ph)
    #   wps  -> push (wff ps)
    #   ax-1 -> pop both, push conclusion
    out_src = append_p_block(
        mm_src=mm_src,
        label="sanity.02",
        stmt="|- ( ph -> ( ps -> ph ) )",
        proof_labels=["wph", "wps", "ax-1"],
        comment="generated by Step 02 (stack machine sanity)",
    )

    with tempfile.TemporaryDirectory() as td:
        out_mm = Path(td) / "out.mm"
        out_mm.write_text(out_src, encoding="utf-8")
        verify(mmverify_py, out_mm, timeout_sec=30)

    print("SANITY 02 OK")


if __name__ == "__main__":
    main()
