# tools/sanity/check_03_mandatory_f.py

import argparse
import tempfile
from pathlib import Path

from proof_scaffold.mm_emit import append_p_block
from proof_scaffold.mm_min import load_mm_min, required_f_labels
from proof_scaffold.verify import verify


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mmverify", required=True)
    ap.add_argument("--mini", default="fixtures/sanity/03_mandatory_f.mm")
    args = ap.parse_args()

    mm_verifier = Path(args.mmverify).resolve()
    mini_path = Path(args.mini).resolve()

    mm_src = mini_path.read_text(encoding="utf-8")

    db = load_mm_min(mini_path)
    prereq = required_f_labels(db, "ax-1")
    out_src = append_p_block(
        mm_src=mm_src,
        label="sanity.03",
        stmt="|- ( ph -> ( ps -> ph ) )",
        proof_labels=prereq + ["ax-1"],
        comment="generated by Step 03 (mandatory $f sanity)",
    )

    with tempfile.TemporaryDirectory() as td:
        out_mm = Path(td) / "out.mm"
        out_mm.write_text(out_src, encoding="utf-8")
        verify(mm_verifier, out_mm, timeout_sec=30)

    print("SANITY OK")


if __name__ == "__main__":
    main()
